# This file is used to enable GitHub Sponsors
github: [your-github-username] # GitHub Sponsors
patreon: your-patreon-username # Patreon
open_collective: your-collective-name # Open Collective
ko_fi: your-ko-fi-username # Ko-fi
liberapay: your-liberapay-username # Liberapay
custom: https://example.com # Any other donation link
