# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json
blank_issues_enabled: false
contact_links:
  - name: Ask the community
    url: https://flockmod.com/r/nlobby4
    about: Try asking the community for help with your issue.
