.TH EREBUS 1 "April 23, 2025" "Erebus CLI" "User Commands"
.SH NAME
erebus \- A CLI tool for serving static HTML files
.SH SYNOPSIS
erebus [OPTIONS]
.SH DESCRIPTION
Erebus is a CLI tool for serving static HTML files with configuration support.
.SH OPTIONS
.TP
\fB--help\fR
Display this help message and exit.
.TP
\fB--version\fR
Display the version of the CLI tool and exit.
.SH AUTHOR
Your Name
.SH COPYRIGHT
Copyright 2025 Your Name
